#!/usr/bin/env bash
# Copies a local file to a remote server using scp with a specified SSH key (disables host key checking)

if [ "$4" == "" ]
then 
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    host="$3@$2:~/"
    scp -o StrictHostKeyChecking=no -i $4 $1 $host
fi