#!/usr/bin/env bash
# Transfers a file from client to server using scp

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4

# Construct destination (user@ip:~/)
DESTINATION="${USERNAME}@${SERVER_IP}:~/"

# Perform secure copy
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$DESTINATION"