#!/usr/bin/env bash
# Install nginx web server

set -euo pipefail

sudo apt-get update -y
sudo apt-get install -y nginx

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
sudo sed -i 's/\(listen \)[0-9]\+\(.*\)/\180\2/' /etc/nginx/sites-available/default

echo "Holberton School for the win!" | sudo tee /var/www/html/index.html > /dev/null

sudo systemctl restart nginx